### ISSUE TITLE
Not able to update an exam

### ISSUE THREAD

**Issue by sudhannsu** [amirhamza05/Student-Management-System#10]
Fatal error: Uncaught Error: Cannot use object of type exam as array in C:\xampp\htdocs\mis\page_action\exam\exam_action.php:61 Stack trace: #0 C:\xampp\htdocs\mis\exam_action.php(5): include() #1 {main} thrown in C:\xampp\htdocs\mis\page_action\exam\exam_action.php on line 61

**Comment by amirhamza05** [comment]
I already running updating exam feature.Please wait for few days for update version.
