### ISSUE TITLE
Setting info incorrect

### ISSUE THREAD

**Issue by eyesoftbd** [amirhamza05/Student-Management-System#11]
### **in setting table {Database}**

1 | site_name | -> It is ok.
2 | sort_name | -> It is ok.
3 | address | -> It is ok.
4 | phone | -> It was replaced with Main Logo file.
5 | email | -> It was replaced with Logo file.
6 | logo | -> It was replaced with Phone no.
7 | main_logo | -> It was replaced with Email Address.
8 | msg | -> I don't know this.

_**by default there are no record in this table. As the result no record can be saved in this. When I added manually ['option_name'], then worked. So, I think sql need to be update with ['option_name'] withing blank record or your record. But working fine. Without this section login failed. After added in setting table in database login worked.**_

**Comment by amirhamza05** [comment]
Thanks for issue.I already update my sql file and added all default option name.

**Comment by PerumalD** [comment]
sql.sql file is empty

**Comment by amirhamza05** [comment]
Check install_sql.sql it is main sql file.

**Comment by PerumalD** [comment]
What is the username and password?

**Comment by amirhamza05** [comment]
You need to make a new password using php sha function and replace any user table password by your new password.

**Comment by nasiruusmanj** [comment]
> ### **in setting table {Database}**
> 1 | site_name | -> It is ok.
> 2 | sort_name | -> It is ok.
> 3 | address | -> It is ok.
> 4 | phone | -> It was replaced with Main Logo file.
> 5 | email | -> It was replaced with Logo file.
> 6 | logo | -> It was replaced with Phone no.
> 7 | main_logo | -> It was replaced with Email Address.
> 8 | msg | -> I don't know this.
> 
> _**by default there are no record in this table. As the result no record can be saved in this. When I added manually ['option_name'], then worked. So, I think sql need to be update with ['option_name'] withing blank record or your record. But working fine. Without this section login failed. After added in setting table in database login worked.**_

Please sir can you explain more because I'm facing the same issue.

**Comment by PVIJAYSIMHAREDDY** [comment]
Notice: Undefined offset: 0 in /opt/lampp/htdocs/sms/config/connect.php on line 66

Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 66

Notice: Undefined offset: 1 in /opt/lampp/htdocs/sms/config/connect.php on line 67

Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 67

Notice: Undefined offset: 2 in /opt/lampp/htdocs/sms/config/connect.php on line 68

Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 68

Notice: Undefined offset: 5 in /opt/lampp/htdocs/sms/config/connect.php on line 69

Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 69

Notice: Undefined offset: 6 in /opt/lampp/htdocs/sms/config/connect.php on line 70

Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 70

Notice: Undefined offset: 4 in /opt/lampp/htdocs/sms/config/connect.php on line 71

Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 71

Notice: Undefined offset: 3 in /opt/lampp/htdocs/sms/config/connect.php on line 72

Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 72

Notice: Undefined offset: 1 in /opt/lampp/htdocs/sms/config/connect.php on line 73

**Comment by eyesoftbd** [comment]
PLEASE GO TO PHPMYADMIN AND ADD MANUALLY INFORMATION TO DATABASE, IT WILL FIX ALL. Sent from Mail for Windows 10 From: PVIJAYSIMHAREDDYSent: Thursday, August 27, 2020 3:07 AMTo: amirhamza05/Student-Management-SystemCc: EyeSoftBD Devs; AuthorSubject: Re: [amirhamza05/Student-Management-System] Setting info incorrect (#11) Notice: Undefined offset: 0 in /opt/lampp/htdocs/sms/config/connect.php on line 66Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 66Notice: Undefined offset: 1 in /opt/lampp/htdocs/sms/config/connect.php on line 67Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 67Notice: Undefined offset: 2 in /opt/lampp/htdocs/sms/config/connect.php on line 68Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 68Notice: Undefined offset: 5 in /opt/lampp/htdocs/sms/config/connect.php on line 69Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 69Notice: Undefined offset: 6 in /opt/lampp/htdocs/sms/config/connect.php on line 70Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 70Notice: Undefined offset: 4 in /opt/lampp/htdocs/sms/config/connect.php on line 71Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 71Notice: Undefined offset: 3 in /opt/lampp/htdocs/sms/config/connect.php on line 72Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 72Notice: Undefined offset: 1 in /opt/lampp/htdocs/sms/config/connect.php on line 73—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by eyesoftbd** [comment]
### Please Visit 

> 
> 
> i am getting this error and if i disable "set_institute_info " ,iam able to login but again i am getting error in add exam
> Notice: Undefined offset: 0 in /opt/lampp/htdocs/sms/config/connect.php on line 66
> 
> Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 66
> 
> Notice: Undefined offset: 1 in /opt/lampp/htdocs/sms/config/connect.php on line 67
> 
> Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 67
> 
> Notice: Undefined offset: 2 in /opt/lampp/htdocs/sms/config/connect.php on line 68
> 
> Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 68
> 
> Notice: Undefined offset: 5 in /opt/lampp/htdocs/sms/config/connect.php on line 69
> 
> Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 69
> 
> Notice: Undefined offset: 6 in /opt/lampp/htdocs/sms/config/connect.php on line 70
> 
> Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 70
> 
> Notice: Undefined offset: 4 in /opt/lampp/htdocs/sms/config/connect.php on line 71
> 
> Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 71
> 
> Notice: Undefined offset: 3 in /opt/lampp/htdocs/sms/config/connect.php on line 72
> 
> Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 72
> 
> Notice: Undefined offset: 1 in /opt/lampp/htdocs/sms/config/connect.php on line 73

### Please visit PHPMYADMIN and add site information manually and it will be ok.

**Comment by eyesoftbd** [comment]
> 
> 
> i am getting this error and if i disable "set_institute_info " ,iam able to login but again i am getting error in add exam
> Notice: Undefined offset: 0 in /opt/lampp/htdocs/sms/config/connect.php on line 66
> 
> Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 66
> 
> Notice: Undefined offset: 1 in /opt/lampp/htdocs/sms/config/connect.php on line 67
> 
> Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 67
> 
> Notice: Undefined offset: 2 in /opt/lampp/htdocs/sms/config/connect.php on line 68
> 
> Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 68
> 
> Notice: Undefined offset: 5 in /opt/lampp/htdocs/sms/config/connect.php on line 69
> 
> Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 69
> 
> Notice: Undefined offset: 6 in /opt/lampp/htdocs/sms/config/connect.php on line 70
> 
> Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 70
> 
> Notice: Undefined offset: 4 in /opt/lampp/htdocs/sms/config/connect.php on line 71
> 
> Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 71
> 
> Notice: Undefined offset: 3 in /opt/lampp/htdocs/sms/config/connect.php on line 72
> 
> Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 72
> 
> Notice: Undefined offset: 1 in /opt/lampp/htdocs/sms/config/connect.php on line 73

https://github.com/amirhamza05/Student-Management-System/issues/11?_pjax=%23js-repo-pjax-container#issuecomment-620832499

**Comment by PVIJAYSIMHAREDDY** [comment]
where should i add site information , i mean in which data i need to add

**Comment by eyesoftbd** [comment]
Follow as first comment above. You just need to change some value of setting table in database.

**Comment by PVIJAYSIMHAREDDY** [comment]
i am really sorry , i am new to this , could you please share the code through email ,bunty_peddi50@gmail.com

**Comment by eyesoftbd** [comment]
Your mail address not found, please knock me.

**Comment by PVIJAYSIMHAREDDY** [comment]
can you please send it on buntypeddi0@gmail.com

**Comment by sutejym122** [comment]
how and where to add site information manually??

**Comment by eyesoftbd** [comment]
Have you solved it?
If not mail me directly. eyesoftbd@gmail.com

**Comment by amirhamza05** [comment]
In the current updated version, this problem is solved. You just clone this system then install database like instruction and use it easily.
