### ISSUE TITLE
Error On login page load

### ISSUE THREAD

**Issue by codesigood** [amirhamza05/Student-Management-System#13]
Please i recieve below error when try to run the project help
Notice: Undefined offset: 0 in C:\xampp\htdocs\astess\config\connect.php on line 67

Notice: Undefined offset: 1 in C:\xampp\htdocs\astess\config\connect.php on line 68

Notice: Undefined offset: 2 in C:\xampp\htdocs\astess\config\connect.php on line 69

Notice: Undefined offset: 5 in C:\xampp\htdocs\astess\config\connect.php on line 70

Notice: Undefined offset: 6 in C:\xampp\htdocs\astess\config\connect.php on line 71

Notice: Undefined offset: 4 in C:\xampp\htdocs\astess\config\connect.php on line 72

Notice: Undefined offset: 3 in C:\xampp\htdocs\astess\config\connect.php on line 73

Notice: Undefined offset: 1 in C:\xampp\htdocs\astess\config\connect.php on line 74

**Comment by amirhamza05** [comment]
Update db file with your database.

**Comment by DRabindra** [comment]
same problem i faced how to solve it will you please elaborate..

**Comment by sutejym122** [comment]
can you please elaborate it @amirhamza05  or you can mail me @ sutejym122@gmail.com

**Comment by amirhamza05** [comment]
In the current updated version, this problem is solved. You just clone this system then install database like instruction and use it easily.
