### ISSUE TITLE
Can't add new exam 

### ISSUE THREAD

**Issue by sultanafghan** [amirhamza05/Student-Management-System#15]
when want to add new exam it show this error :

Fatal error: Cannot use object of type database as array in C:\xampp\htdocs\SMS\page\exam\exam_list.php on line 40

**Comment by amirhamza05** [comment]
Sorry i can not work exam option for this versiton.I work exam feature in new version. As soon as possible i upload this version.

**Comment by naman-150200** [comment]
Exam can not been added please help

**Comment by amirhamza05** [comment]
You can use [this version](https://github.com/amirhamza05/Student-Management-System/tree/a4154763e1263c1e4f214933fd93d5e20550311e). I work exam feature in [this version](https://github.com/amirhamza05/Student-Management-System/tree/a4154763e1263c1e4f214933fd93d5e20550311e). But current version i update remove exam feature for updating.

**Comment by naman-150200** [comment]
By using this version all the previous functionality disappeared . Kindly
help
