### ISSUE TITLE
HI hamza 

### ISSUE THREAD

**Issue by sunnystark** [amirhamza05/Student-Management-System#2]
i did seen your entire work its good. i ve to upgrade some module like 

logout button.
fees collection 
student login 
user delete 
student wise fees name 
print receipt 

___________________________

these module not implement yet in your sms 

:)  if you want to work with me  ping me on  my mail id sunnystark19@gmail.com

**Comment by amirhamza05** [comment]
Hi sunnystark,
Thanks for your Feedback.I already add those module.
