### ISSUE TITLE
connect.php issue

### ISSUE THREAD

**Issue by PVIJAYSIMHAREDDY** [amirhamza05/Student-Management-System#23]
if i disable public function set_institute_info iam able to login but other modules are not working properly 

Notice: Undefined offset: 0 in /opt/lampp/htdocs/sms/config/connect.php on line 66

Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 66

Notice: Undefined offset: 1 in /opt/lampp/htdocs/sms/config/connect.php on line 67

Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 67

Notice: Undefined offset: 2 in /opt/lampp/htdocs/sms/config/connect.php on line 68

Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 68

Notice: Undefined offset: 5 in /opt/lampp/htdocs/sms/config/connect.php on line 69

Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 69

Notice: Undefined offset: 6 in /opt/lampp/htdocs/sms/config/connect.php on line 70

Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 70

Notice: Undefined offset: 4 in /opt/lampp/htdocs/sms/config/connect.php on line 71

Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 71

Notice: Undefined offset: 3 in /opt/lampp/htdocs/sms/config/connect.php on line 72

Notice: Trying to access array offset on value of type null in /opt/lampp/htdocs/sms/config/connect.php on line 72

Notice: Undefined offset: 1 in /opt/lampp/htdocs/sms/config/connect.php on line 73

**Comment by amirhamza05** [comment]
change config/db.php config.

**Comment by sutejym122** [comment]
same problem how to solve this?

**Comment by amirhamza05** [comment]
In the current updated version, this problem is solved. You just clone this system then install database like instruction and use it easily.
