### ISSUE TITLE
Not Adding New User

### ISSUE THREAD

**Issue by SanketChheladiya** [amirhamza05/Student-Management-System#25]
![Screenshot (188)](https://user-images.githubusercontent.com/63163171/92322342-41c89080-f04e-11ea-9c56-1cacba692cf6.png)
![Screenshot (188)](https://user-images.githubusercontent.com/63163171/92322352-53119d00-f04e-11ea-8e2e-6fcbadf26034.png)

There are No submit button option

**Comment by amirhamza05** [comment]
Currently add user feature is not available. I wish next update i added it.

**Comment by SanketChheladiya** [comment]
How can I add multiple batch in one student????
Plz tell me

**Comment by amirhamza05** [comment]
Go to student profile and add program.

**Comment by SanketChheladiya** [comment]
How can I sand message?
It says you do not set any gatways.
Can you provide any gatways?

**Comment by amirhamza05** [comment]
i use local sms gateway. in most of gateway provide api with token. You can replace gateway url with your local gateway api url and replace token with your local api token and use it.
