### ISSUE TITLE
What is the admin password

### ISSUE THREAD

**Issue by Gaxmining** [amirhamza05/Student-Management-System#26]

**Comment by amirhamza05** [comment]
replace admin password field with your custom password using php sha function.

**Comment by jrichardsz** [comment]
Password is 12345678

**Comment by jaymar0813** [comment]
Sir Amir, the function subjects are not included
![image](https://user-images.githubusercontent.com/71686014/103146967-49da4680-478b-11eb-95d8-fec936a7820d.png)

**Comment by amirhamza05** [comment]
You can add subjects and program manually.

**Comment by ngalande** [comment]
> Password is 12345678

Which username

**Comment by amirhamza05** [comment]
In the current updated version, this problem is solved. You just clone this system then install database like instruction and use it easily.
