### ISSUE TITLE
How to add Sms Api ?

### ISSUE THREAD

**Issue by EvilRodez** [amirhamza05/Student-Management-System#34]
is there a way i can add Api in this and messages start working for real

**Comment by amirhamza05** [comment]
Yes, you can add your local API for messages. Please follow the SMS script.

**Comment by EvilRodez** [comment]
can uh guide me?
on more thing why are the students not showing up in batches or attendance.

**Comment by amirhamza05** [comment]
Firstly you add students in particular program batches then you see the student list in attendance. If you don't add a program then added a program. After added the program then added batches. 1 program has multiple batches. Then you can add any student to a particular program.
