### ISSUE TITLE
Hello i got error when run... and login to admin page!!!!

### ISSUE THREAD

**Issue by ElectroArmy** [amirhamza05/Student-Management-System#4]
Warning: Use of undefined constant localhost - assumed 'localhost' (this will throw an Error in a future version of PHP) in D:\xampp\htdocs\Student-Management-System\layout\header_script.php on line 8

Warning: Use of undefined constant root - assumed 'root' (this will throw an Error in a future version of PHP) in D:\xampp\htdocs\Student-Management-System\layout\header_script.php on line 8

Warning: Use of undefined constant root - assumed 'root' (this will throw an Error in a future version of PHP) in D:\xampp\htdocs\Student-Management-System\layout\header_script.php on line 8

Warning: Use of undefined constant youth - assumed 'youth' (this will throw an Error in a future version of PHP) in D:\xampp\htdocs\Student-Management-System\layout\header_script.php on line 8

**Comment by amirhamza05** [comment]
You must change our database name.Go to config->db and replace database name and password.
